framework:
    validation:
        enable_annotations: true  # Make sure this is present globally
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        # auto_mapping:
        #     App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
            enable_annotations: true
